### PR TITLE
Port to Python 3 and WeeWX V4

### PR DESCRIPTION
**Pull request by tkeffer**
I also added an optparse-driven test capability.

### CODE REVIEW

**Comment by tkeffer** [comment]
Oh, I also refactored it to take better advantage of the internal machinery in `restx.RESTThread`

**Comment by tkeffer** [comment]
Now uses `restx.get_site_dict()`. This allows the use of the keyword `enable`, as well as set up default values for `log_success` and `log_failure`

**Comment by tkeffer** [comment]
This one is still pending...

**Comment by knackko** [comment]
Damn I did not see this pull request before I try to update the files today !

**Review by knackko — APPROVED** [review]
Tested, changes work with python3 and weewx 4.0 !

**Pull request merged**
